// ============================================================
// HFLS data.js - 소방시설 연혁 법령 지원 시스템 데이터
// 기준: 소방시설 설치 및 관리에 관한 법률 시행령
//       (대통령령 제36220호, 2026.03.24 시행)
// 출처: 소방시설 설치 및 관리에 관한 법률 시행령 별표2·별표4
// ============================================================

// ─────────────────────────────────────────────
// 1. 법령 버전 메타데이터
// ─────────────────────────────────────────────
export const LAW_VERSIONS = [
  {
    law_name: "소방시설 설치 및 관리에 관한 법률 시행령",
    version_id: "LAW_FIRE_DECREE_20260324",
    promulgation_date: "2026-03-24",
    effective_date: "2026-03-24",
    decree_number: "제36220호",
    amendment_type: "일부개정",
    amendment_reason: "자체점검 점검자의 기술등급 구분 정비 및 규제 재검토기한 정비",
    source_doc: "소방시설 설치 및 관리에 관한 법률 시행령(대통령령)(제36220호)(20260324).pdf",
  },
  {
    law_name: "소방시설 설치 및 관리에 관한 법률",
    version_id: "LAW_FIRE_DECREE_20241201",
    promulgation_date: "2021-11-30",
    effective_date: "2022-12-01",
    decree_number: "제18522호",
    amendment_type: "전부개정",
    amendment_reason: "화재예방과 소방시설 설치·관리 체계 분리 및 법령 체계 전면 개편",
    source_doc: "소방시설 설치 및 관리에 관한 법률(법률)(제18522호)(20241201).pdf",
  },
  {
    law_name: "화재예방, 소방시설 설치ㆍ유지 및 안전관리에 관한 법률 시행령",
    version_id: "LAW_FIRE_MAINT_20170126",
    promulgation_date: "2017-01-26",
    effective_date: "2017-01-26",
    decree_number: null,
    amendment_type: "일부개정",
    amendment_reason: "소방시설 설치기준 강화 및 내연수 소방용품(분말소화기 10년) 설정",
    source_doc: "[통합]화재예방, 소방시설법 시행령.pdf",
  },
  {
    law_name: "소방법 시행령",
    version_id: "LAW_OLD_DECREE_19630811",
    promulgation_date: "1963-07-11",
    effective_date: "1963-08-11",
    decree_number: null,
    amendment_type: "제정",
    amendment_reason: "소방법 시행에 필요한 초기 세부 사항 규정",
    source_doc: "[통합]소방법 시행령.pdf",
  },
];

// ─────────────────────────────────────────────
// 2. 별표2 — 특정소방대상물 분류
//    기준: LAW_FIRE_DECREE_20260324 (2026.03.24)
// ─────────────────────────────────────────────
export const BUILDING_TYPES = [
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 2",
    category_no: "1",
    category_name: "공동주택",
    sub_items: [
      {
        sub_no: "가",
        name: "아파트등",
        condition: "주택으로 쓰는 층수가 5층 이상인 주택",
        exclusion: null,
        note: null,
      },
      {
        sub_no: "나",
        name: "연립주택",
        condition:
          "주택으로 쓰는 1개 동의 바닥면적(2개 이상의 동을 지하주차장으로 연결하는 경우에는 각각의 동으로 본다) 합계가 660㎡를 초과하고, 층수가 4개 층 이하인 주택",
        exclusion: null,
        note: null,
      },
      {
        sub_no: "다",
        name: "다세대주택",
        condition:
          "주택으로 쓰는 1개 동의 바닥면적(2개 이상의 동을 지하주차장으로 연결하는 경우에는 각각의 동으로 본다) 합계가 660㎡ 이하이고, 층수가 4개 층 이하인 주택",
        exclusion: null,
        note: null,
      },
      {
        sub_no: "라",
        name: "기숙사",
        condition:
          "학교 또는 공장 등의 학생 또는 종업원 등을 위하여 쓰는 것으로서 1개 동의 공동취사시설 이용 세대 개수가 전체의 50퍼센트 이상인 것",
        exclusion: "「공동주택관리법 시행령」 제2조제1항제4호에 따른 행복주택 등 제외",
        note: null,
      },
    ],
  },
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 2",
    category_no: "2",
    category_name: "근린생활시설",
    sub_items: [
      {
        sub_no: "가",
        name: "의원, 치과의원, 한의원, 침술원, 접골원, 조산원, 산후조리원",
        condition: null,
        exclusion: null,
        note: null,
      },
      {
        sub_no: "나",
        name: "공연장",
        condition: "바닥면적의 합계가 300㎡ 미만인 것",
        exclusion: null,
        note: null,
      },
      {
        sub_no: "다",
        name: "급수식당, 극장, 영화상영관",
        condition: "바닥면적의 합계가 300㎡ 미만인 것",
        exclusion: null,
        note: null,
      },
    ],
  },
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 2",
    category_no: "3",
    category_name: "문화 및 집회시설",
    sub_items: [
      {
        sub_no: "가",
        name: "공연장",
        condition:
          "극장, 영화상영관, 연예장, 음악당, 서커스장, 비디오물소극장, 그 밖에 이와 비슷한 것으로서 근린생활시설에 해당하지 않는 것",
        exclusion: null,
        note: null,
      },
      {
        sub_no: "나",
        name: "집회장",
        condition:
          "예식장, 공회당, 회의장, 마권 장외 발매소, 마권 전화투표소, 그 밖에 이와 비슷한 것으로서 근린생활시설에 해당하지 않는 것",
        exclusion: null,
        note: null,
      },
      {
        sub_no: "다",
        name: "관람장",
        condition:
          "경마장, 경륜장, 경정장, 자동차 경기장, 그 밖에 이와 비슷한 것과 체육관 및 운동장으로서 관람석 바닥면적의 합계가 1,000㎡ 이상인 것",
        exclusion: null,
        note: null,
      },
      {
        sub_no: "라",
        name: "전시장",
        condition:
          "박물관, 미술관, 과학관, 문화관, 체험관, 기념관, 산업전시장, 박람회장, 그 밖에 이와 비슷한 것",
        exclusion: null,
        note: null,
      },
      {
        sub_no: "마",
        name: "동물원 및 식물원",
        condition: "동물원, 식물원, 수족관, 그 밖에 이와 비슷한 것",
        exclusion: null,
        note: null,
      },
    ],
  },
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 2",
    category_no: "4",
    category_name: "종교시설",
    sub_items: [
      {
        sub_no: "가",
        name: "종교집회장",
        condition:
          "교회, 성당, 사찰, 기도원, 사당, 그 밖에 이와 비슷한 것으로서 근린생활시설에 해당하지 않는 것",
        exclusion: null,
        note: null,
      },
      {
        sub_no: "나",
        name: "봉안당",
        condition:
          "「장사 등에 관한 법률」 제2조제9호에 따른 봉안당으로서 종교시설에 설치하는 것",
        exclusion: null,
        note: null,
      },
    ],
  },
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 2",
    category_no: "5",
    category_name: "판매시설",
    sub_items: [
      {
        sub_no: "가",
        name: "도매시장",
        condition:
          "「농수산물 유통 및 가격안정에 관한 법률」에 따른 농수산물도매시장, 농수산물공판장, 그 밖에 이와 비슷한 것(그 안에 있는 근린생활시설을 포함한다)",
        exclusion: null,
        note: null,
      },
      {
        sub_no: "나",
        name: "소매시장",
        condition:
          "「유통산업발전법」 제2조제3호에 따른 대규모점포, 그 밖에 이와 비슷한 것(그 안에 있는 근린생활시설을 포함한다)",
        exclusion: null,
        note: null,
      },
      {
        sub_no: "다",
        name: "전통시장",
        condition:
          "「전통시장 및 상점가 육성을 위한 특별법」 제2조제1호에 따른 전통시장",
        exclusion: null,
        note: null,
      },
      {
        sub_no: "라",
        name: "상점",
        condition:
          "근린생활시설에 해당하지 않는 것으로서 식품·잡화·의류·완구·서적·의약품·의료기기 등 물품을 판매하는 점포",
        exclusion: null,
        note: null,
      },
    ],
  },
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 2",
    category_no: "6",
    category_name: "운수시설",
    sub_items: [
      {
        sub_no: "가",
        name: "여객자동차터미널",
        condition: "「여객자동차 운수사업법」에 따른 여객자동차터미널",
        exclusion: null,
        note: null,
      },
      {
        sub_no: "나",
        name: "철도시설",
        condition: "역사, 철도차량 정비시설 및 그 밖에 이와 비슷한 것",
        exclusion: null,
        note: null,
      },
      {
        sub_no: "다",
        name: "공항시설",
        condition:
          "여객터미널, 화물터미널, 계류장, 항공기 격납고, 그 밖에 이와 비슷한 것",
        exclusion: null,
        note: null,
      },
      {
        sub_no: "라",
        name: "항만시설",
        condition: "여객이용시설, 항만관련 업무시설, 그 밖에 이와 비슷한 것",
        exclusion: null,
        note: null,
      },
    ],
  },
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 2",
    category_no: "7",
    category_name: "의료시설",
    sub_items: [
      {
        sub_no: "가",
        name: "병원",
        condition:
          "종합병원, 병원, 치과병원, 한의원, 요양병원(의료재활시설은 제외한다)",
        exclusion: null,
        note: null,
      },
      {
        sub_no: "나",
        name: "격리병원",
        condition: "전염병원, 마약진료소, 그 밖에 이와 비슷한 것",
        exclusion: null,
        note: null,
      },
      {
        sub_no: "다",
        name: "정신의료기관",
        condition:
          "「정신건강증진 및 정신질환자 복지서비스 지원에 관한 법률」 제3조제5호가목에 따른 정신병원",
        exclusion: null,
        note: null,
      },
      {
        sub_no: "라",
        name: "장애인 의료재활시설",
        condition: "「장애인복지법」 제58조제1항제4호에 따른 시설",
        exclusion: null,
        note: null,
      },
    ],
  },
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 2",
    category_no: "8",
    category_name: "교육연구시설",
    sub_items: [
      {
        sub_no: "가",
        name: "학교",
        condition:
          "초등학교, 중학교, 고등학교, 전문대학, 대학, 대학교, 그 밖에 이와 비슷한 것",
        exclusion: null,
        note: null,
      },
      {
        sub_no: "나",
        name: "교육원",
        condition: "연수원, 그 밖에 이와 비슷한 것",
        exclusion: null,
        note: null,
      },
      {
        sub_no: "다",
        name: "직업훈련소",
        condition: "근린생활시설에 해당하지 않는 것",
        exclusion: null,
        note: null,
      },
      {
        sub_no: "라",
        name: "학원",
        condition:
          "자동차학원·무도학원 및 정보통신기술을 활용하여 원격으로 교습하는 것은 제외하며, 근린생활시설에 해당하지 않는 것",
        exclusion: null,
        note: null,
      },
      {
        sub_no: "마",
        name: "연구소",
        condition: "기업부설연구소 등을 포함한다",
        exclusion: null,
        note: null,
      },
      {
        sub_no: "바",
        name: "도서관",
        condition: null,
        exclusion: null,
        note: null,
      },
    ],
  },
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 2",
    category_no: "9",
    category_name: "노유자 시설",
    sub_items: [
      {
        sub_no: "가",
        name: "아동 관련 시설",
        condition:
          "어린이집, 아동복지시설, 그 밖에 이와 비슷한 것으로서 거주 및 보호 기능이 있는 것",
        exclusion: "유치원은 교육연구시설임",
        note: null,
      },
      {
        sub_no: "나",
        name: "노인 관련 시설",
        condition:
          "「노인복지법」에 따른 노인주거복지시설, 노인의료복지시설, 노인여가복지시설, 주·야간보호서비스나 단기보호서비스를 제공하는 재가노인복지시설",
        exclusion: null,
        note: null,
      },
      {
        sub_no: "다",
        name: "장애인 관련 시설",
        condition:
          "「장애인복지법」에 따른 장애인 거주시설, 장애인 지역사회재활시설(의료재활시설은 의료시설임), 장애인 직업재활시설",
        exclusion: null,
        note: null,
      },
      {
        sub_no: "라",
        name: "정신질환자 관련 시설",
        condition:
          "「정신건강복지법」에 따른 정신건강증진시설(정신의료기관은 제외), 정신재활시설, 정신요양시설",
        exclusion: null,
        note: null,
      },
      {
        sub_no: "마",
        name: "노숙인 관련 시설",
        condition:
          "「노숙인 복지 및 자립 지원에 관한 법률」 제2조제2호에 따른 노숙인복지시설(노숙인일시보호시설, 노숙인자활시설, 노숙인재활시설, 노숙인요양시설, 노숙인급식시설 및 노숙인진료시설)",
        exclusion: null,
        note: null,
      },
    ],
  },
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 2",
    category_no: "10",
    category_name: "수련시설",
    sub_items: [
      {
        sub_no: "가",
        name: "생활권 수련시설",
        condition:
          "청소년수련관, 청소년문화의집, 청소년특화시설, 그 밖에 이와 비슷한 것",
        exclusion: null,
        note: null,
      },
      {
        sub_no: "나",
        name: "자연권 수련시설",
        condition: "청소년수련원, 청소년야영장, 그 밖에 이와 비슷한 것",
        exclusion: null,
        note: null,
      },
      {
        sub_no: "다",
        name: "유스호스텔",
        condition: "「청소년 활동 진흥법」 제10조제1호라목에 따른 시설",
        exclusion: null,
        note: null,
      },
    ],
  },
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 2",
    category_no: "11",
    category_name: "운동시설",
    sub_items: [
      {
        sub_no: "가",
        name: "탁구장, 테니스장, 볼링장, 당구장, 실내낚시터, 골프연습장, 물놀이형 시설",
        condition: "그 밖에 이와 비슷한 것으로서 근린생활시설에 해당하지 않는 것",
        exclusion: null,
        note: null,
      },
      {
        sub_no: "나",
        name: "체육관",
        condition: "관람석 바닥면적의 합계가 1,000㎡ 미만인 것",
        exclusion: null,
        note: null,
      },
      {
        sub_no: "다",
        name: "운동장",
        condition:
          "육상장, 축구장, 야구장, 양궁장, 사격장, 승마장, 씨름장, 농구장, 배구장, 그 밖에 이와 비슷한 것으로서 관람석 바닥면적의 합계가 1,000㎡ 미만인 것",
        exclusion: null,
        note: null,
      },
    ],
  },
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 2",
    category_no: "12",
    category_name: "업무시설",
    sub_items: [
      {
        sub_no: "가",
        name: "공공업무시설",
        condition:
          "국가 또는 지방자치단체의 청사와 외국공관의 건축물로서 근린생활시설에 해당하지 않는 것",
        exclusion: null,
        note: null,
      },
      {
        sub_no: "나",
        name: "일반업무시설",
        condition:
          "금융업소, 사무소, 신문사, 오피스텔(업무를 주로 하며, 분양하거나 임대하는 구획 중 일부 구획에서 숙식을 할 수 있도록 한 건축물로서 국토교통부장관이 고시하는 기준에 적합한 것), 그 밖에 이와 비슷한 것으로서 근린생활시설에 해당하지 않는 것",
        exclusion: null,
        note: null,
      },
    ],
  },
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 2",
    category_no: "13",
    category_name: "숙박시설",
    sub_items: [
      {
        sub_no: "가",
        name: "일반숙박시설 및 생활숙박시설",
        condition: null,
        exclusion: null,
        note: null,
      },
      {
        sub_no: "나",
        name: "관광숙박시설",
        condition:
          "호텔, 수상관광호텔, 한국전통호텔, 가족호텔, 호스텔, 소형호텔, 의료관광호텔 및 휴양 콘도미니엄",
        exclusion: null,
        note: null,
      },
      {
        sub_no: "다",
        name: "다중이용업소 중 고시원업",
        condition: "근린생활시설에 해당하지 않는 것",
        exclusion: null,
        note: null,
      },
      {
        sub_no: "라",
        name: "그 밖에 가목부터 다목까지의 시설과 비슷한 것",
        condition: null,
        exclusion: null,
        note: null,
      },
    ],
  },
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 2",
    category_no: "14",
    category_name: "위락시설",
    sub_items: [
      {
        sub_no: "가",
        name: "단란주점",
        condition: "근린생활시설에 해당하지 않는 것",
        exclusion: null,
        note: null,
      },
      {
        sub_no: "나",
        name: "유흥주점",
        condition: "그 밖에 이와 비슷한 것(음악접대업을 포함한다)",
        exclusion: null,
        note: null,
      },
      {
        sub_no: "다",
        name: "유원시설업의 시설",
        condition:
          "「관광진흥법」에 따른 유원시설업의 시설, 그 밖에 이와 비슷한 것(근린생활시설에 해당하지 않는 것)",
        exclusion: null,
        note: null,
      },
      {
        sub_no: "라",
        name: "무도장 및 무도학원",
        condition: null,
        exclusion: null,
        note: null,
      },
      {
        sub_no: "마",
        name: "카지노영업소",
        condition: null,
        exclusion: null,
        note: null,
      },
    ],
  },
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 2",
    category_no: "15",
    category_name: "공장",
    sub_items: [
      {
        sub_no: null,
        name: "공장",
        condition:
          "물품의 제조·가공[염색·도장(塗裝)·표백·재봉·인쇄·제분(製粉) 등을 포함한다] 또는 수리에 계속적으로 이용되는 건축물로서 자동차 정비공장, 어구수선장, 데이터센터 및 「산업집적활성화 및 공장설립에 관한 법률」 제28조에 따른 지식산업센터 등 이와 비슷한 것",
        exclusion: null,
        note: null,
      },
    ],
  },
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 2",
    category_no: "16",
    category_name: "창고시설",
    sub_items: [
      {
        sub_no: "가",
        name: "창고",
        condition:
          "물품저장시설로서 「건축법 시행령」 별표 1 제18호가목에 따른 창고(냉장·냉동창고를 포함한다)",
        exclusion: null,
        note: null,
      },
      { sub_no: "나", name: "하역장", condition: null, exclusion: null, note: null },
      {
        sub_no: "다",
        name: "물류터미널",
        condition:
          "「물류시설의 개발 및 운영에 관한 법률」 제2조제2호에 따른 물류터미널",
        exclusion: null,
        note: null,
      },
      {
        sub_no: "라",
        name: "집배송 시설",
        condition: "「유통산업발전법」 제2조제15호에 따른 집배송 시설",
        exclusion: null,
        note: null,
      },
    ],
  },
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 2",
    category_no: "17",
    category_name: "위험물 저장 및 처리 시설",
    sub_items: [
      {
        sub_no: "가",
        name: "위험물 제조소등",
        condition:
          "「위험물 안전관리법」 제2조제1항제6호에 따른 위험물 제조소, 저장소 및 취급소",
        exclusion: null,
        note: null,
      },
      {
        sub_no: "나",
        name: "가스시설",
        condition:
          "「도시가스사업법」, 「고압가스 안전관리법」 또는 「액화석유가스의 안전관리 및 사업법」에 따른 가스제조·저장 및 판매 시설",
        exclusion: null,
        note: null,
      },
      {
        sub_no: "다",
        name: "그 밖에 이와 비슷한 시설",
        condition:
          "주유소(기계식 세차설비를 포함한다), 석유판매소 및 액화석유가스 충전소·판매소·저장소 등",
        exclusion: null,
        note: null,
      },
    ],
  },
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 2",
    category_no: "18",
    category_name: "항공기 및 자동차 관련 시설",
    sub_items: [
      { sub_no: "가", name: "항공기 격납고", condition: null, exclusion: null, note: null },
      {
        sub_no: "나",
        name: "차고, 주차장",
        condition: "주차전용 건축물을 포함한다",
        exclusion: null,
        note: null,
      },
      { sub_no: "다", name: "세차장", condition: null, exclusion: null, note: null },
      { sub_no: "라", name: "폐차장", condition: null, exclusion: null, note: null },
      { sub_no: "마", name: "검사장", condition: null, exclusion: null, note: null },
      { sub_no: "바", name: "매매장", condition: null, exclusion: null, note: null },
      { sub_no: "사", name: "정비공장", condition: null, exclusion: null, note: null },
      {
        sub_no: "아",
        name: "운전학원 및 정비학원",
        condition: null,
        exclusion: null,
        note: null,
      },
      {
        sub_no: "자",
        name: "여객용 시설 및 화물용 시설",
        condition:
          "「건축법 시행령」 별표 1 제20호자목에 따른 시설로서 운수시설에 해당하지 않는 것",
        exclusion: null,
        note: null,
      },
    ],
  },
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 2",
    category_no: "19",
    category_name: "동물 및 식물 관련 시설",
    sub_items: [
      { sub_no: "가", name: "축사", condition: null, exclusion: null, note: null },
      {
        sub_no: "나",
        name: "가축시설",
        condition: "가축용 운동시설, 인공수정센터, 관리사, 에이아이(AI)센터 등",
        exclusion: null,
        note: null,
      },
      { sub_no: "다", name: "도축장", condition: null, exclusion: null, note: null },
      { sub_no: "라", name: "도계장", condition: null, exclusion: null, note: null },
      {
        sub_no: "마",
        name: "작물 재배사",
        condition: "버섯재배사, 종묘배양시설 등",
        exclusion: null,
        note: null,
      },
      {
        sub_no: "바",
        name: "화초 및 분재 등의 온실",
        condition: null,
        exclusion: null,
        note: null,
      },
      {
        sub_no: "사",
        name: "동물 및 식물과 관련된 가목부터 바목까지의 시설과 비슷한 것",
        condition: null,
        exclusion: "동물원 및 식물원은 제외한다",
        note: null,
      },
    ],
  },
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 2",
    category_no: "20",
    category_name: "자원순환 관련 시설",
    sub_items: [
      {
        sub_no: "가",
        name: "하수 등 처리시설",
        condition: "하수처리시설, 분뇨처리시설, 축산폐수처리시설 등",
        exclusion: null,
        note: null,
      },
      { sub_no: "나", name: "고물상", condition: null, exclusion: null, note: null },
      {
        sub_no: "다",
        name: "폐기물 재활용 시설",
        condition: null,
        exclusion: null,
        note: null,
      },
      {
        sub_no: "라",
        name: "폐기물 처분 시설",
        condition: null,
        exclusion: null,
        note: null,
      },
      {
        sub_no: "마",
        name: "폐기물 감량화 시설",
        condition: null,
        exclusion: null,
        note: null,
      },
    ],
  },
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 2",
    category_no: "21",
    category_name: "교정 및 군사 시설",
    sub_items: [
      {
        sub_no: "가",
        name: "교정시설",
        condition: "교도소, 구치소 및 그 부속시설",
        exclusion: null,
        note: null,
      },
      {
        sub_no: "나",
        name: "갱생보호시설",
        condition: "그 밖에 범죄자의 갱생·보육·교육·보건 등의 용도로 쓰는 시설",
        exclusion: null,
        note: null,
      },
      {
        sub_no: "다",
        name: "소년원 및 소년분류심사원",
        condition: null,
        exclusion: null,
        note: null,
      },
      {
        sub_no: "라",
        name: "국방·군사시설",
        condition: null,
        exclusion: null,
        note: null,
      },
    ],
  },
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 2",
    category_no: "22",
    category_name: "방송통신시설",
    sub_items: [
      {
        sub_no: "가",
        name: "방송국",
        condition: "방송국, 전신전화국, 촬영소, 그 밖에 이와 비슷한 것",
        exclusion: null,
        note: null,
      },
      {
        sub_no: "나",
        name: "통신용 송수신탑",
        condition: null,
        exclusion: null,
        note: null,
      },
      {
        sub_no: "다",
        name: "데이터센터",
        condition: "가목 및 나목에 해당하지 않는 것",
        exclusion: null,
        note: null,
      },
    ],
  },
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 2",
    category_no: "23",
    category_name: "발전시설",
    sub_items: [
      {
        sub_no: null,
        name: "발전시설",
        condition:
          "원자력발전소, 화력발전소, 수력발전소, 풍력발전소, 태양력발전소, 조력발전소, 그 밖에 이와 비슷한 것",
        exclusion: "변전소",
        note: null,
      },
    ],
  },
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 2",
    category_no: "24",
    category_name: "묘지 관련 시설",
    sub_items: [
      { sub_no: "가", name: "화장시설", condition: null, exclusion: null, note: null },
      {
        sub_no: "나",
        name: "봉안당",
        condition: "종교시설에 설치하는 것은 제외한다",
        exclusion: "종교시설 내 봉안당",
        note: null,
      },
      {
        sub_no: "다",
        name: "묘지와 부수되는 건축물",
        condition: null,
        exclusion: null,
        note: null,
      },
      {
        sub_no: "라",
        name: "자연장지에 부수되는 건축물",
        condition: null,
        exclusion: null,
        note: null,
      },
      {
        sub_no: "마",
        name: "동물화장시설, 동물건조장시설 및 동물 전용의 봉안시설",
        condition: null,
        exclusion: null,
        note: null,
      },
    ],
  },
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 2",
    category_no: "25",
    category_name: "관광 휴게시설",
    sub_items: [
      { sub_no: "가", name: "야외음악당", condition: null, exclusion: null, note: null },
      { sub_no: "나", name: "야외극장", condition: null, exclusion: null, note: null },
      { sub_no: "다", name: "어린이회관", condition: null, exclusion: null, note: null },
      { sub_no: "라", name: "관망탑", condition: null, exclusion: null, note: null },
      { sub_no: "마", name: "휴게소", condition: null, exclusion: null, note: null },
      {
        sub_no: "바",
        name: "공원·관광지 또는 휴양지에 부수되는 시설",
        condition: null,
        exclusion: null,
        note: null,
      },
    ],
  },
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 2",
    category_no: "26",
    category_name: "장례시설",
    sub_items: [
      {
        sub_no: "가",
        name: "장례식장",
        condition: "의료시설의 부수시설은 제외한다",
        exclusion: "의료시설 부수 장례식장",
        note: null,
      },
      {
        sub_no: "나",
        name: "동물장례식장",
        condition: null,
        exclusion: null,
        note: null,
      },
    ],
  },
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 2",
    category_no: "27",
    category_name: "지하가",
    sub_items: [
      {
        sub_no: "가",
        name: "지하상가",
        condition:
          "지하의 인공구조물 안에 설치된 상점 및 사무실, 그 밖에 이와 비슷한 시설이 연속하여 지하도에 접하여 설치된 것과 그 지하도를 합한 것",
        exclusion: null,
        note: null,
      },
      {
        sub_no: "나",
        name: "터널",
        condition: "차량 등의 통행을 위하여 지하, 해저 또는 산을 뚫어 만든 구조물",
        exclusion: null,
        note: null,
      },
    ],
  },
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 2",
    category_no: "28",
    category_name: "지하구",
    sub_items: [
      {
        sub_no: null,
        name: "지하구",
        condition:
          "전력·통신용 전선이나 가스·냉난방용 배관 또는 이와 비슷한 것을 집합 수용하기 위하여 설치한 지하 인공구조물로서 사람이 점검·보수를 하기 위하여 출입이 가능한 것(폭 1.8m 이상, 높이 2m 이상, 길이 50m 이상인 것)",
        exclusion: null,
        note: null,
      },
    ],
  },
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 2",
    category_no: "29",
    category_name: "문화재",
    sub_items: [
      {
        sub_no: null,
        name: "문화재",
        condition:
          "「문화재보호법」에 따라 지정된 국보 또는 보물로 지정된 목조건축물",
        exclusion: null,
        note: null,
      },
    ],
  },
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 2",
    category_no: "30",
    category_name: "복합건축물",
    sub_items: [
      {
        sub_no: null,
        name: "복합건축물",
        condition:
          "하나의 건축물이 별표 2 제1호부터 제29호까지의 것 중 둘 이상의 용도로 사용되는 것",
        exclusion: "아파트등의 용도와 그 외의 용도가 복합된 경우 포함",
        note: null,
      },
    ],
  },
];

// ─────────────────────────────────────────────
// 3. 별표4 — 소방시설 설치기준
//    기준: LAW_FIRE_DECREE_20260324 (2026.03.24)
// ─────────────────────────────────────────────
export const FACILITY_REQUIREMENTS = [
  // ── 소화설비 ─────────────────────────────
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 4",
    facility_category: "소화설비",
    facility_type: "소화기구",
    applicable_buildings: [
      {
        item_no: "1)가)",
        building_category_no: "all",
        building_name: "특정소방대상물",
        threshold_area_m2: 33,
        threshold_area_condition: "이상",
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text: "연면적 33㎡ 이상인 것",
        is_mandatory: true,
        exception_clause: null,
      },
      {
        item_no: "1)나)",
        building_category_no: "29",
        building_name: "지정문화재",
        threshold_area_m2: null,
        threshold_area_condition: null,
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text: "「문화재보호법」에 따라 지정된 문화재",
        is_mandatory: true,
        exception_clause: null,
      },
      {
        item_no: "1)다)",
        building_category_no: "17-나",
        building_name: "가스시설",
        threshold_area_m2: null,
        threshold_area_condition: null,
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text: "가스시설",
        is_mandatory: true,
        exception_clause: null,
      },
      {
        item_no: "1)라)",
        building_category_no: "27-나",
        building_name: "터널",
        threshold_area_m2: null,
        threshold_area_condition: null,
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text: "터널",
        is_mandatory: true,
        exception_clause: null,
      },
      {
        item_no: "1)마)",
        building_category_no: "28",
        building_name: "지하구",
        threshold_area_m2: null,
        threshold_area_condition: null,
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text: "지하구",
        is_mandatory: true,
        exception_clause: null,
      },
    ],
  },
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 4",
    facility_category: "소화설비",
    facility_type: "자동소화장치",
    applicable_buildings: [
      {
        item_no: "2)가)",
        building_category_no: "1-가",
        building_name: "아파트등",
        threshold_area_m2: null,
        threshold_area_condition: null,
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text: "아파트등의 각 세대별 주방",
        is_mandatory: true,
        exception_clause: null,
      },
      {
        item_no: "2)나)",
        building_category_no: "30",
        building_name: "복합건축물",
        threshold_area_m2: null,
        threshold_area_condition: null,
        threshold_floor: 30,
        threshold_floor_condition: "이상",
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text: "30층 이상인 복합건축물의 각 세대별 주방",
        is_mandatory: true,
        exception_clause: null,
      },
    ],
  },
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 4",
    facility_category: "소화설비",
    facility_type: "옥내소화전설비",
    applicable_buildings: [
      {
        item_no: "3)가)",
        building_category_no: "all",
        building_name: "특정소방대상물",
        threshold_area_m2: 3000,
        threshold_area_condition: "이상",
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text: "연면적 3천㎡ 이상(지하가 중 터널은 제외한다)인 것의 모든 층",
        is_mandatory: true,
        exception_clause: "축사 제외",
      },
      {
        item_no: "3)나)",
        building_category_no: "all",
        building_name: "지하층·무창층 또는 4층 이상인 층",
        threshold_area_m2: 600,
        threshold_area_condition: "이상",
        threshold_floor: 4,
        threshold_floor_condition: "이상",
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text:
          "지하층·무창층 또는 층수가 4층 이상인 층 중 바닥면적이 600㎡ 이상인 층이 있는 것의 모든 층",
        is_mandatory: true,
        exception_clause: null,
      },
      {
        item_no: "3)다)",
        building_category_no: "27-나",
        building_name: "터널",
        threshold_area_m2: null,
        threshold_area_condition: null,
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text: "지하가 중 터널로서 길이가 1,000m 이상인 터널",
        is_mandatory: true,
        exception_clause: null,
      },
      {
        item_no: "3)라)",
        building_category_no: "28",
        building_name: "지하구",
        threshold_area_m2: null,
        threshold_area_condition: null,
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text:
          "지하구(「국토의 계획 및 이용에 관한 법률」 제2조제9호에 따른 공동구는 제외한다)",
        is_mandatory: true,
        exception_clause: null,
      },
    ],
  },
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 4",
    facility_category: "소화설비",
    facility_type: "스프링클러설비",
    applicable_buildings: [
      {
        item_no: "4)가)",
        building_category_no: "all",
        building_name: "6층 이상 건축물",
        threshold_area_m2: null,
        threshold_area_condition: null,
        threshold_floor: 6,
        threshold_floor_condition: "이상",
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text: "층수가 6층 이상인 특정소방대상물의 모든 층",
        is_mandatory: true,
        exception_clause: "아파트등 제외(별도 규정)",
      },
      {
        item_no: "4)나)",
        building_category_no: "3,4,11",
        building_name: "문화 및 집회시설, 종교시설, 운동시설",
        threshold_area_m2: 5000,
        threshold_area_condition: "이상",
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: 500,
        threshold_capacity_condition: "이상",
        condition_text: "연면적 5천㎡ 이상이거나 수용인원이 500명 이상인 것의 모든 층",
        is_mandatory: true,
        exception_clause: "동물원 및 식물원 제외",
      },
      {
        item_no: "4)다)",
        building_category_no: "5,6,16",
        building_name: "판매시설, 운수시설, 창고시설(물류터미널)",
        threshold_area_m2: 5000,
        threshold_area_condition: "이상",
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: 500,
        threshold_capacity_condition: "이상",
        condition_text: "연면적 5천㎡ 이상이거나 수용인원이 500명 이상인 것의 모든 층",
        is_mandatory: true,
        exception_clause: null,
      },
      {
        item_no: "4)라)",
        building_category_no: "7,9",
        building_name: "의료시설(종합병원 등), 노유자 시설",
        threshold_area_m2: 600,
        threshold_area_condition: "이상",
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text: "연면적 600㎡ 이상인 것의 모든 층",
        is_mandatory: true,
        exception_clause: null,
      },
    ],
  },
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 4",
    facility_category: "소화설비",
    facility_type: "간이스프링클러설비",
    applicable_buildings: [
      {
        item_no: "5)가)",
        building_category_no: "2-가,9",
        building_name: "근린생활시설(의원 등), 노유자 시설",
        threshold_area_m2: 600,
        threshold_area_condition: "미만",
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text:
          "연면적 600㎡ 미만인 노유자 시설(단독경보형 감지기를 설치하는 경우는 제외)",
        is_mandatory: true,
        exception_clause: null,
      },
      {
        item_no: "5)나)",
        building_category_no: "7-가",
        building_name: "의료시설(요양병원)",
        threshold_area_m2: 600,
        threshold_area_condition: "미만",
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text:
          "연면적 600㎡ 미만인 요양병원(정신병원 및 의료재활시설은 제외)",
        is_mandatory: true,
        exception_clause: null,
      },
    ],
  },
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 4",
    facility_category: "소화설비",
    facility_type: "물분무등소화설비",
    applicable_buildings: [
      {
        item_no: "6)가)",
        building_category_no: "18-가",
        building_name: "항공기 격납고",
        threshold_area_m2: null,
        threshold_area_condition: null,
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text: "항공기 격납고",
        is_mandatory: true,
        exception_clause: null,
      },
      {
        item_no: "6)나)",
        building_category_no: "18-나",
        building_name: "주차용 건축물",
        threshold_area_m2: 800,
        threshold_area_condition: "이상",
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text: "연면적 800㎡ 이상인 주차전용 건축물",
        is_mandatory: true,
        exception_clause: null,
      },
      {
        item_no: "6)다)",
        building_category_no: "22",
        building_name: "방송통신시설",
        threshold_area_m2: 500,
        threshold_area_condition: "이상",
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text:
          "바닥면적의 합계가 500㎡ 이상인 전기실·발전실·변전실·축전지실·통신기기실 또는 전산실",
        is_mandatory: true,
        exception_clause: null,
      },
    ],
  },
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 4",
    facility_category: "소화설비",
    facility_type: "옥외소화전설비",
    applicable_buildings: [
      {
        item_no: "7)가)",
        building_category_no: "all",
        building_name: "특정소방대상물",
        threshold_area_m2: 9000,
        threshold_area_condition: "이상",
        threshold_floor: 1,
        threshold_floor_condition: "이상",
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text:
          "지상 1층 및 2층의 바닥면적의 합계가 9천㎡ 이상인 특정소방대상물",
        is_mandatory: true,
        exception_clause: "아파트등 제외",
      },
      {
        item_no: "7)나)",
        building_category_no: "29",
        building_name: "보물 또는 국보로 지정된 목조건축물",
        threshold_area_m2: null,
        threshold_area_condition: null,
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text:
          "「문화재보호법」에 따른 보물 또는 국보로 지정된 목조건축물",
        is_mandatory: true,
        exception_clause: null,
      },
    ],
  },

  // ── 경보설비 ─────────────────────────────
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 4",
    facility_category: "경보설비",
    facility_type: "비상경보설비",
    applicable_buildings: [
      {
        item_no: "2)가)1)",
        building_category_no: "all",
        building_name: "특정소방대상물",
        threshold_area_m2: 400,
        threshold_area_condition: "이상",
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text: "연면적 400㎡ 이상(지하가 중 터널은 제외한다)인 것",
        is_mandatory: true,
        exception_clause: null,
      },
      {
        item_no: "2)가)2)",
        building_category_no: "all",
        building_name: "지하층 또는 무창층",
        threshold_area_m2: 150,
        threshold_area_condition: "이상",
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text:
          "지하층 또는 무창층의 바닥면적이 150㎡(공연장인 경우에는 100㎡) 이상인 것",
        is_mandatory: true,
        exception_clause: null,
      },
      {
        item_no: "2)가)3)",
        building_category_no: "all",
        building_name: "특정소방대상물",
        threshold_area_m2: null,
        threshold_area_condition: null,
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: 50,
        threshold_capacity_condition: "이상",
        condition_text: "수용인원이 50명 이상인 것",
        is_mandatory: true,
        exception_clause: null,
      },
      {
        item_no: "2)가)4)",
        building_category_no: "27-나",
        building_name: "터널",
        threshold_area_m2: null,
        threshold_area_condition: null,
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text: "지하가 중 터널로서 길이가 500m 이상인 것",
        is_mandatory: true,
        exception_clause: null,
      },
    ],
  },
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 4",
    facility_category: "경보설비",
    facility_type: "단독경보형 감지기",
    applicable_buildings: [
      {
        item_no: "2)나)1)",
        building_category_no: "1",
        building_name: "연면적 1,000㎡ 미만의 아파트등 및 기숙사",
        threshold_area_m2: 1000,
        threshold_area_condition: "미만",
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text: "연면적 1,000㎡ 미만의 아파트등 및 기숙사",
        is_mandatory: true,
        exception_clause: null,
      },
      {
        item_no: "2)나)2)",
        building_category_no: "8,9",
        building_name: "교육연구시설 또는 수련시설 내의 합숙소",
        threshold_area_m2: 2000,
        threshold_area_condition: "미만",
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text:
          "교육연구시설 또는 수련시설 내에 있는 합숙소 또는 기숙사로서 연면적 2,000㎡ 미만인 것",
        is_mandatory: true,
        exception_clause: null,
      },
      {
        item_no: "2)나)3)",
        building_category_no: "9",
        building_name: "연면적 600㎡ 미만의 노유자 시설",
        threshold_area_m2: 600,
        threshold_area_condition: "미만",
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text: "연면적 600㎡ 미만인 노유자 시설",
        is_mandatory: true,
        exception_clause: null,
      },
      {
        item_no: "2)나)4)",
        building_category_no: "13",
        building_name: "연면적 600㎡ 미만의 숙박시설",
        threshold_area_m2: 600,
        threshold_area_condition: "미만",
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text: "연면적 600㎡ 미만인 숙박시설",
        is_mandatory: true,
        exception_clause: null,
      },
    ],
  },
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 4",
    facility_category: "경보설비",
    facility_type: "자동화재탐지설비",
    applicable_buildings: [
      {
        item_no: "2)다)1)",
        building_category_no: "2,7,9,13,14,26,30",
        building_name: "근린생활시설, 위락시설, 숙박시설, 의료시설, 노유자 시설, 장례시설, 복합건축물",
        threshold_area_m2: 600,
        threshold_area_condition: "이상",
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text: "연면적 600㎡ 이상인 것",
        is_mandatory: true,
        exception_clause:
          "의료시설 중 정신의료기관, 요양병원, 노유자 시설 중 노유자 생활시설은 제외(모든 층 설치 대상)",
      },
      {
        item_no: "2)다)2)",
        building_category_no: "1,7,9",
        building_name: "공동주택, 정신의료기관, 요양병원, 노유자 생활시설",
        threshold_area_m2: null,
        threshold_area_condition: null,
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text:
          "공동주택(아파트등 및 기숙사), 의료시설 중 정신의료기관 및 요양병원, 노유자 시설 중 노유자 생활시설의 모든 층",
        is_mandatory: true,
        exception_clause: null,
      },
      {
        item_no: "2)다)3)",
        building_category_no: "3,4,5,6,8,10,11,12,19,20,21,22,23,24,25",
        building_name: "문화 및 집회시설, 종교시설, 판매시설, 운수시설, 운동시설, 업무시설, 교육연구시설 등",
        threshold_area_m2: 1000,
        threshold_area_condition: "이상",
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text: "연면적 1,000㎡ 이상인 것",
        is_mandatory: true,
        exception_clause: "교정 및 군사시설 중 교도소 등은 제외",
      },
      {
        item_no: "2)다)4)",
        building_category_no: "8,10",
        building_name: "교육연구시설 또는 수련시설 내의 합숙소",
        threshold_area_m2: 2000,
        threshold_area_condition: "이상",
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text:
          "교육연구시설 또는 수련시설 내에 있는 합숙소 또는 기숙사로서 연면적 2,000㎡ 이상인 것",
        is_mandatory: true,
        exception_clause: null,
      },
      {
        item_no: "2)다)5)",
        building_category_no: "27-나",
        building_name: "터널",
        threshold_area_m2: null,
        threshold_area_condition: null,
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text: "지하가 중 터널로서 길이가 1,000m 이상인 터널",
        is_mandatory: true,
        exception_clause: null,
      },
      {
        item_no: "2)다)6)",
        building_category_no: "28",
        building_name: "지하구",
        threshold_area_m2: null,
        threshold_area_condition: null,
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text: "지하구",
        is_mandatory: true,
        exception_clause: null,
      },
    ],
  },
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 4",
    facility_category: "경보설비",
    facility_type: "시각경보기",
    applicable_buildings: [
      {
        item_no: "2)라)",
        building_category_no: "all",
        building_name: "자동화재탐지설비 설치 대상 중 특정 용도",
        threshold_area_m2: null,
        threshold_area_condition: null,
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text:
          "자동화재탐지설비를 설치해야 하는 특정소방대상물 중 근린생활시설, 문화 및 집회시설, 종교시설, 판매시설, 운수시설, 의료시설, 노유자 시설, 수련시설, 운동시설, 업무시설, 숙박시설, 위락시설, 발전시설, 장례시설, 방송국, 도서관, 지하가(지하상가)",
        is_mandatory: true,
        exception_clause: null,
      },
    ],
  },
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 4",
    facility_category: "경보설비",
    facility_type: "자동화재속보설비",
    applicable_buildings: [
      {
        item_no: "2)마)1)",
        building_category_no: "12,15,16,23,30",
        building_name: "업무시설, 공장, 창고시설, 발전시설, 복합건축물",
        threshold_area_m2: 1500,
        threshold_area_condition: "이상",
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text: "바닥면적이 1,500㎡ 이상인 층이 있는 것",
        is_mandatory: true,
        exception_clause: "방재실 등 수신기가 설치된 장소에 24시간 근무자가 있는 경우 제외",
      },
      {
        item_no: "2)마)2)",
        building_category_no: "9",
        building_name: "노유자 생활시설",
        threshold_area_m2: null,
        threshold_area_condition: null,
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text: "노유자 생활시설",
        is_mandatory: true,
        exception_clause: null,
      },
      {
        item_no: "2)마)3)",
        building_category_no: "9",
        building_name: "노유자 시설",
        threshold_area_m2: 500,
        threshold_area_condition: "이상",
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text: "연면적 500㎡ 이상인 노유자 시설(노유자 생활시설은 제외)",
        is_mandatory: true,
        exception_clause: null,
      },
      {
        item_no: "2)마)4)",
        building_category_no: "7-가",
        building_name: "의료시설(요양병원)",
        threshold_area_m2: 500,
        threshold_area_condition: "미만",
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text:
          "연면적 500㎡ 미만인 요양병원(정신병원 및 의료재활시설은 제외)",
        is_mandatory: true,
        exception_clause: null,
      },
    ],
  },
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 4",
    facility_category: "경보설비",
    facility_type: "가스누설경보기",
    applicable_buildings: [
      {
        item_no: "2)바)1)",
        building_category_no: "17-나",
        building_name: "가스시설",
        threshold_area_m2: null,
        threshold_area_condition: null,
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text: "가스시설이 설치된 특정소방대상물",
        is_mandatory: true,
        exception_clause: null,
      },
      {
        item_no: "2)바)2)",
        building_category_no: "28",
        building_name: "지하구",
        threshold_area_m2: null,
        threshold_area_condition: null,
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text: "지하구",
        is_mandatory: true,
        exception_clause: null,
      },
    ],
  },
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 4",
    facility_category: "경보설비",
    facility_type: "통합감시시설",
    applicable_buildings: [
      {
        item_no: "2)사)",
        building_category_no: "all",
        building_name: "공동구로 연결된 특정소방대상물 등",
        threshold_area_m2: null,
        threshold_area_condition: null,
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text:
          "둘 이상의 특정소방대상물이 공동구로 연결되어 있거나 내화구조의 복도 등으로 연결되어 소방청장이 정하여 고시하는 연합 점검이 필요한 대상물",
        is_mandatory: true,
        exception_clause: null,
      },
    ],
  },

  // ── 피난구조설비 ──────────────────────────
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 4",
    facility_category: "피난구조설비",
    facility_type: "피난기구",
    applicable_buildings: [
      {
        item_no: "3)가)",
        building_category_no: "all",
        building_name: "특정소방대상물",
        threshold_area_m2: null,
        threshold_area_condition: null,
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text: "특정소방대상물의 모든 층에 설치할 것",
        is_mandatory: true,
        exception_clause:
          "피난층, 지상 1층, 지상 2층 및 층수가 11층 이상인 층은 제외(노유자시설, 의료시설 중 피난이 어려운 시설은 별도 화재안전기준에 따름)",
      },
    ],
  },
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 4",
    facility_category: "피난구조설비",
    facility_type: "인명구조기구",
    applicable_buildings: [
      {
        item_no: "3)나)1)",
        building_category_no: "27-가",
        building_name: "지하가 중 지하상가",
        threshold_area_m2: null,
        threshold_area_condition: null,
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text: "지하가 중 지하상가",
        is_mandatory: true,
        exception_clause: "방열복 또는 방화복, 공기호흡기 및 인공소생기를 설치할 것",
      },
      {
        item_no: "3)나)2)",
        building_category_no: "13-나",
        building_name: "7층 이상 특정소방대상물 중 관광호텔",
        threshold_area_m2: null,
        threshold_area_condition: null,
        threshold_floor: 7,
        threshold_floor_condition: "이상",
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text: "층수가 7층 이상인 특정소방대상물 중 관광호텔 용도로 사용하는 층",
        is_mandatory: true,
        exception_clause: "방열복 또는 방화복, 공기호흡기 및 인공소생기를 설치할 것",
      },
      {
        item_no: "3)나)3)",
        building_category_no: "7-가",
        building_name: "의료시설 중 병원",
        threshold_area_m2: null,
        threshold_area_condition: null,
        threshold_floor: 5,
        threshold_floor_condition: "이상",
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text: "층수가 5층 이상인 특정소방대상물 중 병원 용도로 사용하는 층",
        is_mandatory: true,
        exception_clause: "방열복 또는 방화복, 공기호흡기 및 인공소생기를 설치할 것",
      },
    ],
  },
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 4",
    facility_category: "피난구조설비",
    facility_type: "유도등",
    applicable_buildings: [
      {
        item_no: "3)다)",
        building_category_no: "all",
        building_name: "특정소방대상물",
        threshold_area_m2: null,
        threshold_area_condition: null,
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text:
          "피난구유도등, 통로유도등 및 유도표지는 특정소방대상물에 설치할 것",
        is_mandatory: true,
        exception_clause:
          "축사로서 가축을 직접 사육하는 부분 및 터널은 제외(터널은 화재안전기준에 따름)",
      },
    ],
  },
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 4",
    facility_category: "피난구조설비",
    facility_type: "비상조명등",
    applicable_buildings: [
      {
        item_no: "3)라)1)",
        building_category_no: "all",
        building_name: "특정소방대상물",
        threshold_area_m2: 3000,
        threshold_area_condition: "이상",
        threshold_floor: 5,
        threshold_floor_condition: "이상",
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text: "층수가 5층 이상인 건축물로서 연면적 3천㎡ 이상인 것",
        is_mandatory: true,
        exception_clause: null,
      },
      {
        item_no: "3)라)2)",
        building_category_no: "all",
        building_name: "지하층 또는 무창층",
        threshold_area_m2: 450,
        threshold_area_condition: "이상",
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text: "지하층 또는 무창층으로서 바닥면적이 450㎡ 이상인 층",
        is_mandatory: true,
        exception_clause: null,
      },
      {
        item_no: "3)라)3)",
        building_category_no: "27-나",
        building_name: "터널",
        threshold_area_m2: null,
        threshold_area_condition: null,
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text: "지하가 중 터널로서 길이가 500m 이상인 터널",
        is_mandatory: true,
        exception_clause: null,
      },
    ],
  },
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 4",
    facility_category: "피난구조설비",
    facility_type: "휴대용 비상조명등",
    applicable_buildings: [
      {
        item_no: "3)마)1)",
        building_category_no: "13",
        building_name: "숙박시설",
        threshold_area_m2: null,
        threshold_area_condition: null,
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text: "숙박시설",
        is_mandatory: true,
        exception_clause: null,
      },
      {
        item_no: "3)마)2)",
        building_category_no: "5-나",
        building_name: "소매시장 중 대규모점포",
        threshold_area_m2: null,
        threshold_area_condition: null,
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text: "판매시설 중 대규모점포",
        is_mandatory: true,
        exception_clause: null,
      },
      {
        item_no: "3)마)3)",
        building_category_no: "6-나",
        building_name: "운수시설 중 지하역사",
        threshold_area_m2: null,
        threshold_area_condition: null,
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text: "철도 및 도시철도 시설 중 지하역사",
        is_mandatory: true,
        exception_clause: null,
      },
      {
        item_no: "3)마)4)",
        building_category_no: "27-가",
        building_name: "지하상가",
        threshold_area_m2: null,
        threshold_area_condition: null,
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text: "지하가 중 지하상가",
        is_mandatory: true,
        exception_clause: null,
      },
      {
        item_no: "3)마)5)",
        building_category_no: "3-가",
        building_name: "영화상영관",
        threshold_area_m2: null,
        threshold_area_condition: null,
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: 100,
        threshold_capacity_condition: "이상",
        condition_text: "영화상영관(수용인원 100명 이상인 것)",
        is_mandatory: true,
        exception_clause: null,
      },
    ],
  },

  // ── 소화용수설비 ──────────────────────────
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 4",
    facility_category: "소화용수설비",
    facility_type: "상수도소화용수설비",
    applicable_buildings: [
      {
        item_no: "4)가)",
        building_category_no: "all",
        building_name: "특정소방대상물",
        threshold_area_m2: 5000,
        threshold_area_condition: "이상",
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text: "연면적 5천㎡ 이상인 것",
        is_mandatory: true,
        exception_clause: "가스시설, 지하구 또는 상수도 설치가 곤란한 지역은 제외",
      },
    ],
  },
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 4",
    facility_category: "소화용수설비",
    facility_type: "소화수조 및 저수조",
    applicable_buildings: [
      {
        item_no: "4)나)",
        building_category_no: "all",
        building_name: "상수도 설치가 곤란한 대상물",
        threshold_area_m2: null,
        threshold_area_condition: null,
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text:
          "상수도소화용수설비를 설치해야 하는 특정소방대상물의 대지 경계선으로부터 140m 이내에 호칭지름 75mm 이상인 상수도용 배관이 설치되지 않은 경우",
        is_mandatory: true,
        exception_clause: null,
      },
    ],
  },

  // ── 소화활동설비 ──────────────────────────
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 4",
    facility_category: "소화활동설비",
    facility_type: "제연설비",
    applicable_buildings: [
      {
        item_no: "5)가)1)",
        building_category_no: "3,4,5,6,7,9,11,13,14",
        building_name: "문화 및 집회시설, 종교시설, 판매시설 등",
        threshold_area_m2: 1000,
        threshold_area_condition: "이상",
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text:
          "문화 및 집회시설, 종교시설, 판매시설, 운수시설, 의료시설, 노유자 시설, 운동시설, 숙박시설 및 위락시설 중 무창층의 바닥면적 합계가 1천㎡ 이상인 층",
        is_mandatory: true,
        exception_clause: null,
      },
      {
        item_no: "5)가)2)",
        building_category_no: "27-가",
        building_name: "지하상가",
        threshold_area_m2: 1000,
        threshold_area_condition: "이상",
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text: "지하가(터널은 제외한다)로서 연면적 1천㎡ 이상인 것",
        is_mandatory: true,
        exception_clause: null,
      },
      {
        item_no: "5)가)3)",
        building_category_no: "3-가",
        building_name: "영화상영관",
        threshold_area_m2: null,
        threshold_area_condition: null,
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: 100,
        threshold_capacity_condition: "이상",
        condition_text: "수용인원 100명 이상인 영화상영관",
        is_mandatory: true,
        exception_clause: null,
      },
    ],
  },
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 4",
    facility_category: "소화활동설비",
    facility_type: "연결송수관설비",
    applicable_buildings: [
      {
        item_no: "5)나)1)",
        building_category_no: "all",
        building_name: "5층 이상 건축물",
        threshold_area_m2: 6000,
        threshold_area_condition: "이상",
        threshold_floor: 5,
        threshold_floor_condition: "이상",
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text: "층수가 5층 이상으로서 연면적 6천㎡ 이상인 것",
        is_mandatory: true,
        exception_clause: null,
      },
      {
        item_no: "5)나)2)",
        building_category_no: "all",
        building_name: "7층 이상 건축물",
        threshold_area_m2: null,
        threshold_area_condition: null,
        threshold_floor: 7,
        threshold_floor_condition: "이상",
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text: "층수가 7층 이상인 것",
        is_mandatory: true,
        exception_clause: null,
      },
      {
        item_no: "5)나)3)",
        building_category_no: "27-나",
        building_name: "터널",
        threshold_area_m2: null,
        threshold_area_condition: null,
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text: "지하가 중 길이가 1,000m 이상인 터널",
        is_mandatory: true,
        exception_clause: null,
      },
    ],
  },
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 4",
    facility_category: "소화활동설비",
    facility_type: "연결살수설비",
    applicable_buildings: [
      {
        item_no: "5)다)1)",
        building_category_no: "all",
        building_name: "지하층",
        threshold_area_m2: 150,
        threshold_area_condition: "이상",
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text:
          "지하층의 바닥면적 합계가 150㎡(학교는 700㎡) 이상인 것",
        is_mandatory: true,
        exception_clause: "가스시설 또는 지하구 제외",
      },
      {
        item_no: "5)다)2)",
        building_category_no: "28",
        building_name: "지하구",
        threshold_area_m2: null,
        threshold_area_condition: null,
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text: "지하구",
        is_mandatory: true,
        exception_clause: null,
      },
    ],
  },
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 4",
    facility_category: "소화활동설비",
    facility_type: "비상콘센트설비",
    applicable_buildings: [
      {
        item_no: "5)라)1)",
        building_category_no: "all",
        building_name: "11층 이상 건축물",
        threshold_area_m2: null,
        threshold_area_condition: null,
        threshold_floor: 11,
        threshold_floor_condition: "이상",
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text: "층수가 11층 이상인 것의 11층 이상의 층",
        is_mandatory: true,
        exception_clause: null,
      },
      {
        item_no: "5)라)2)",
        building_category_no: "all",
        building_name: "지하층",
        threshold_area_m2: 1000,
        threshold_area_condition: "이상",
        threshold_floor: 3,
        threshold_floor_condition: "이상",
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text:
          "지하층의 층수가 3층 이상이고 지하층의 바닥면적 합계가 1천㎡ 이상인 것의 모든 지하층",
        is_mandatory: true,
        exception_clause: null,
      },
      {
        item_no: "5)라)3)",
        building_category_no: "27-나",
        building_name: "터널",
        threshold_area_m2: null,
        threshold_area_condition: null,
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text: "지하가 중 길이가 500m 이상인 터널",
        is_mandatory: true,
        exception_clause: null,
      },
    ],
  },
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 4",
    facility_category: "소화활동설비",
    facility_type: "무선통신보조설비",
    applicable_buildings: [
      {
        item_no: "5)마)1)",
        building_category_no: "27-가",
        building_name: "지하상가",
        threshold_area_m2: 1000,
        threshold_area_condition: "이상",
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text: "지하가(터널은 제외한다)로서 연면적 1천㎡ 이상인 것",
        is_mandatory: true,
        exception_clause: null,
      },
      {
        item_no: "5)마)2)",
        building_category_no: "all",
        building_name: "지하층",
        threshold_area_m2: 3000,
        threshold_area_condition: "이상",
        threshold_floor: 3,
        threshold_floor_condition: "이상",
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text:
          "지하층의 바닥면적 합계가 3천㎡ 이상인 것 또는 지하층의 층수가 3층 이상이고 지하층의 바닥면적 합계가 450㎡ 이상인 것의 모든 지하층",
        is_mandatory: true,
        exception_clause: null,
      },
      {
        item_no: "5)마)3)",
        building_category_no: "27-나",
        building_name: "터널",
        threshold_area_m2: null,
        threshold_area_condition: null,
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text: "지하가 중 길이가 500m 이상인 터널",
        is_mandatory: true,
        exception_clause: null,
      },
      {
        item_no: "5)마)4)",
        building_category_no: "28",
        building_name: "공동구",
        threshold_area_m2: null,
        threshold_area_condition: null,
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text: "공동구",
        is_mandatory: true,
        exception_clause: null,
      },
    ],
  },
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    annex_no: "별표 4",
    facility_category: "소화활동설비",
    facility_type: "연소방지설비",
    applicable_buildings: [
      {
        item_no: "5)바)",
        building_category_no: "28",
        building_name: "지하구",
        threshold_area_m2: null,
        threshold_area_condition: null,
        threshold_floor: null,
        threshold_floor_condition: null,
        threshold_capacity: null,
        threshold_capacity_condition: null,
        condition_text: "지하구(공동구 포함)",
        is_mandatory: true,
        exception_clause: null,
      },
    ],
  },
];

// ─────────────────────────────────────────────
// 4. 경과조치 및 소급적용 조항
// ─────────────────────────────────────────────
export const TRANSITIONAL_PROVISIONS = [
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    article_ref: "시행령 제15조제1항",
    provision_type: "증축시특례",
    target_buildings: "증축되는 특정소방대상물",
    content:
      "특정소방대상물이 증축되는 경우에는 기존 부분을 포함한 특정소방대상물 전체에 대하여 증축 당시의 소방시설 설치에 관한 대통령령 또는 화재안전기준을 적용한다. 다만, 기존 부분과 증축 부분이 내화구조로 된 바닥과 벽으로 구획된 경우 등 대통령령으로 정하는 경우에는 기존 부분에 대해서는 증축 당시의 기준을 적용하지 않는다.",
    grace_period_months: null,
  },
  {
    version_id: "LAW_FIRE_DECREE_20260324",
    article_ref: "시행령 제15조제2항",
    provision_type: "용도변경시특례",
    target_buildings: "용도변경되는 특정소방대상물",
    content:
      "특정소방대상물이 용도변경되는 경우에는 용도변경되는 부분에 대해서만 용도변경 당시의 소방시설 설치에 관한 대통령령 또는 화재안전기준을 적용한다. 다만, 용도변경으로 인해 천장·벽·바닥 등의 재료가 화재확산 위험이 커지는 경우 등은 예외로 한다.",
    grace_period_months: null,
  },
  {
    version_id: "LAW_FIRE_DECREE_20241201",
    article_ref: "법 제13조",
    provision_type: "기존건축물적용유예",
    target_buildings: "기존 특정소방대상물",
    content:
      "소방본부장 또는 소방서장은 대통령령 또는 화재안전기준이 변경되어 그 기준이 강화되는 경우 기존의 특정소방대상물에 대하여는 변경 전의 기준을 적용한다. 다만, 소화기구, 비상경보설비, 자동화재속보설비 및 피난구조설비와 노유자시설, 의료시설에 설치하는 소방시설 등 대통령령으로 정하는 경우에는 강화된 기준을 적용한다.",
    grace_period_months: null,
  },
  {
    version_id: "LAW_FIRE_DECREE_20120205",
    article_ref: "부칙 제6조",
    provision_type: "소급적용",
    target_buildings: "노유자시설",
    content:
      "이미 건축이 완료된 노유자시설은 이 영 시행 후 2년 이내에 간이스프링클러설비, 자동화재탐지설비 및 자동화재속보설비를 설치하여야 한다.",
    grace_period_months: 24,
  },
  {
    version_id: "LAW_FIRE_DECREE_20190806",
    article_ref: "부칙 제5조",
    provision_type: "소급적용",
    target_buildings: "의료시설(요양병원)",
    content:
      "기존의 요양병원(정신병원 및 의료재활시설은 제외)은 이 영 시행일부터 3년 이내에 스프링클러설비 또는 간이스프링클러설비, 자동화재탐지설비 및 자동화재속보설비를 화재안전기준에 적합하게 설치하여야 한다.",
    grace_period_months: 36,
  },
];

// ─────────────────────────────────────────────
// 5. 유틸리티 함수
// ─────────────────────────────────────────────

/**
 * 건축허가일 기준으로 적용 가능한 법령 버전을 반환
 * @param {string} permitDate - "YYYY-MM-DD" 형식
 * @returns {object} 해당 날짜에 유효한 법령 버전
 */
export function getVersionByDate(permitDate) {
  const target = new Date(permitDate);
  return LAW_VERSIONS.filter(
    (v) => new Date(v.effective_date) <= target
  ).sort(
    (a, b) => new Date(b.effective_date) - new Date(a.effective_date)
  )[0] || null;
}

/**
 * 건축물 용도 코드로 별표2 분류 정보 조회
 * @param {string} categoryNo - "1", "9", "27-가" 등
 * @returns {object|null}
 */
export function getBuildingType(categoryNo) {
  const base = categoryNo.split("-")[0];
  return BUILDING_TYPES.find((b) => b.category_no === base) || null;
}

/**
 * 건축물 용도 코드와 건축허가일로 설치 의무 소방시설 목록 반환
 * @param {string} categoryNo - 별표2 항목번호
 * @param {string} permitDate - "YYYY-MM-DD"
 * @param {object} buildingSpec - { area_m2, floors, capacity }
 * @returns {Array} 설치 의무 소방시설 목록
 */
export function getRequiredFacilities(categoryNo, permitDate, buildingSpec) {
  const version = getVersionByDate(permitDate);
  if (!version) return [];

  const { area_m2 = 0, floors = 1, capacity = 0 } = buildingSpec;
  const base = categoryNo.split("-")[0];

  return FACILITY_REQUIREMENTS.filter((req) => {
    if (req.version_id !== version.version_id) return false;
    return req.applicable_buildings.some((b) => {
      const catMatch =
        b.building_category_no === "all" ||
        b.building_category_no.split(",").some((c) => c.trim() === base);
      if (!catMatch) return false;

      const areaOk = checkThreshold(
        area_m2,
        b.threshold_area_m2,
        b.threshold_area_condition
      );
      const floorOk = checkThreshold(
        floors,
        b.threshold_floor,
        b.threshold_floor_condition
      );
      const capOk = checkThreshold(
        capacity,
        b.threshold_capacity,
        b.threshold_capacity_condition
      );

      return areaOk && floorOk && capOk;
    });
  });
}

function checkThreshold(value, threshold, condition) {
  if (threshold === null) return true;
  switch (condition) {
    case "이상": return value >= threshold;
    case "초과": return value > threshold;
    case "이하": return value <= threshold;
    case "미만": return value < threshold;
    default: return true;
  }
}
